[[main]]
  name = "Home"
  weight = 10
  url = "https://starfleit.io"

[[main]]
  name = "App"
  url = "https://app.starfleit.io"
  weight = 20

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/starfleit"
  weight = 10

[[social]]
  name = "Discord"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" class=\"feather feather-discord\"><path d=\"M8.3841 17.8139C7.87267 18.5694 7.32483 19.299 6.74256 20C2.57949 19.88 1 17.1439 1 17.1439C1.05917 13.267 1.98694 9.45441 3.71333 5.99357C5.23087 4.7914 7.07997 4.09672 9.00462 4.00571L9.56872 5.32524C10.3744 5.21198 11.1866 5.15282 12 5.14816C12.817 5.15088 13.633 5.20813 14.4426 5.31953L15.0067 4C16.9332 4.09593 18.7825 4.79667 20.2979 6.005C22.0188 9.46331 22.9426 13.2718 23 17.1439C23 17.1439 21.4205 19.88 17.2574 20C16.684 19.3024 16.1455 18.576 15.6441 17.8236M19.2882 16.1671C17.1221 17.2781 15.0258 18.3891 12 18.3891C8.97415 18.3891 6.87795 17.2781 4.71179 16.1671\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M8.92354 14.7899C9.84861 14.7899 10.5985 14.04 10.5985 13.1149C10.5985 12.1899 9.84861 11.4399 8.92354 11.4399C7.99846 11.4399 7.24854 12.1899 7.24854 13.1149C7.24854 14.04 7.99846 14.7899 8.92354 14.7899Z\" fill=\"currentColor\"/><path d=\"M15.0766 14.7899C16.0017 14.7899 16.7516 14.04 16.7516 13.1149C16.7516 12.1899 16.0017 11.4399 15.0766 11.4399C14.1515 11.4399 13.4016 12.1899 13.4016 13.1149C13.4016 14.04 14.1515 14.7899 15.0766 14.7899Z\" fill=\"currentColor\"/></svg>"
  url = "https://discord.com/invite/yypdAsRPYm"
  weight = 20

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/starfleit"
  weight = 30
